import type { ProductWithMeta } from "@/types";

/** Static catalog — homepage works without a database */
export const STATIC_PRODUCTS: ProductWithMeta[] = [
  {
    id: "static-1",
    name: "Forest Cedar Body Wash",
    slug: "forest-cedar-body-wash",
    description:
      "A grounding botanical wash with cedarwood, pine needle, and wild moss.",
    price: 28,
    comparePrice: null,
    category: "BODY_WASH",
    stock: 45,
    images: [],
    ingredients:
      "Coconut oil, hemp seed oil, cedarwood essential oil, pine needle extract, glycerin",
    fragrance: "Forest & Cedar",
    featured: true,
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "static-2",
    name: "Citrus Bloom Bar Soap (3-pack)",
    slug: "citrus-bloom-bar-soap",
    description: "Bright citrus layered with neroli and white florals.",
    price: 22,
    comparePrice: null,
    category: "SOAP",
    stock: 8,
    images: [],
    ingredients:
      "Coconut oil, bergamot essential oil, neroli, mango seed butter, olive oil",
    fragrance: "Citrus Bloom",
    featured: true,
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "static-3",
    name: "Warm Amber Body Lotion",
    slug: "warm-amber-body-lotion",
    description: "Silky hydration with amber resin and shea butter.",
    price: 34,
    comparePrice: null,
    category: "LOTION",
    stock: 31,
    images: [],
    ingredients:
      "Shea butter, rosehip oil, kokum butter, amber resin, vitamin E",
    fragrance: "Warm Amber",
    featured: true,
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "static-4",
    name: "The Full Ritual Gift Set",
    slug: "full-ritual-gift-set",
    description: "Our complete botanical ritual in a hand-wrapped gift box.",
    price: 89,
    comparePrice: 110,
    category: "GIFT_SET",
    stock: 12,
    images: [],
    ingredients:
      "Includes bar soap, body wash, and lotion with shea butter, coconut oil, and cedarwood",
    fragrance: "Warm Amber",
    featured: true,
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "static-5",
    name: "Lavender Oat Sugar Scrub",
    slug: "lavender-oat-sugar-scrub",
    description:
      "Gentle exfoliation with colloidal oat and calming lavender for soft, comforted skin.",
    price: 26,
    comparePrice: null,
    category: "SCRUB",
    stock: 20,
    images: [],
    ingredients:
      "Colloidal oat, coconut oil, lavender essential oil, raw sugar, shea butter",
    fragrance: "Lavender & Oat",
    featured: true,
    active: true,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "static-6",
    name: "Cedarwood Calm Roll-On",
    slug: "cedarwood-calm-roll-on",
    description:
      "A pocket-sized aromatherapy blend for wrists and pulse points before sleep.",
    price: 18,
    comparePrice: null,
    category: "AROMATHERAPY",
    stock: 35,
    images: [],
    ingredients:
      "Cedarwood essential oil, lavender essential oil, hemp seed oil, jojoba",
    fragrance: "Forest & Lavender",
    featured: false,
    active: true,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "static-7",
    name: "Rosehip Renewal Bar Soap",
    slug: "rosehip-renewal-bar-soap",
    description:
      "Nourishing bar with rosehip and mango seed butter for a silky, radiant cleanse.",
    price: 14,
    comparePrice: null,
    category: "SOAP",
    stock: 40,
    images: [],
    ingredients:
      "Rosehip oil, mango seed butter, coconut oil, kokum butter, olive oil",
    fragrance: "Soft Floral",
    featured: true,
    active: true,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-08-01"),
  },
];

export const STATIC_FEATURED = STATIC_PRODUCTS.filter((p) => p.featured);
