import type { ProductWithMeta } from "@/types";

/** Static catalog — homepage works without a database */
export const STATIC_PRODUCTS: ProductWithMeta[] = [
  {
    id: "static-1",
    name: "Forest Cedar Body Wash",
    slug: "forest-cedar-body-wash",
    description:
      "A grounding botanical wash with cedarwood, pine needle, and wild moss.",
    price: 28,
    comparePrice: null,
    category: "BODY_WASH",
    stock: 45,
    images: [],
    ingredients: null,
    fragrance: "Forest & Cedar",
    featured: true,
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "static-2",
    name: "Citrus Bloom Bar Soap (3-pack)",
    slug: "citrus-bloom-bar-soap",
    description: "Bright citrus layered with neroli and white florals.",
    price: 22,
    comparePrice: null,
    category: "SOAP",
    stock: 8,
    images: [],
    ingredients: null,
    fragrance: "Citrus Bloom",
    featured: true,
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "static-3",
    name: "Warm Amber Body Lotion",
    slug: "warm-amber-body-lotion",
    description: "Silky hydration with amber resin and shea butter.",
    price: 34,
    comparePrice: null,
    category: "LOTION",
    stock: 31,
    images: [],
    ingredients: null,
    fragrance: "Warm Amber",
    featured: true,
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "static-4",
    name: "The Full Ritual Gift Set",
    slug: "full-ritual-gift-set",
    description: "Our complete botanical ritual in a hand-wrapped gift box.",
    price: 89,
    comparePrice: 110,
    category: "GIFT_SET",
    stock: 12,
    images: [],
    ingredients: null,
    fragrance: "Warm Amber",
    featured: true,
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const STATIC_FEATURED = STATIC_PRODUCTS.filter((p) => p.featured);
